[package]
name = "fuzzy"
version = "0.1.0"
edition = "2024"

[dependencies]
paste = "1.0.15"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.16"
fake = "4.2.0"
insta = { version = "1.42.2", features = ["yaml"] }
