name: "Check Program"

on:
	pull_request:
		types:
			- opened
			- synchronize
	push:
		branches:
			- master
	workflow_dispatch:

jobs:
	check:
		runs-on: ubuntu-latest

		steps:
			- name: Checkout repository
			  uses: actions/checkout@v3

			- name: Setup Rust
			  uses: dtolnay/rust-toolchain@stable

			- name: Check format
			  run: cargo fmt --check

			- name: Check Clippy
			  run: rustup component add clippy && cargo clippy

			- name: Check test
			  run: cargo test

			- name: Check build
			  run: cargo build --release
