name: "Check Program"

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check format
        run: cargo fmt --check

      - name: Check Clippy
        run: rustup component add clippy && cargo clippy --no-deps -- --deny warnings

      - name: Check tests
        run: cargo test

      - name: Check build
        run: cargo build --release
